[package]
name = "umlparser"
version = "0.1.0"
authors = ["jtissen1 <jakob.tissen@fh-bielefeld.de>"]

[dependencies]
rocket = "0.3.2"
rocket_codegen = "0.3.2"
rocket_contrib = { version = "0.3.2", default-features = false, features = ["tera_templates"] }

tera = "0.10"